version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    ports:
      - 5601:5601
    networks:
      - es
networks:
  es:
    driver: bridge